MODEL_PATH = "yolo"
MIN_CONF = 0.4
NMS_THRESH = 0.4
DISPLAY = True
OUTPUT = True
THRESHOLD = 15
USE_GPU = False
ALERT = True
MAIL = ''

URL = 0
MIN_DISTANCE = 40
CV_INP_WIDTH = 416
CV_INP_HEIGHT = 416
# WEIGHTS = "yolov3.weights"
# CFG = "yolov3.cfg"
WEIGHTS = "yolov4-tiny.weights"
CFG = "yolov4-tiny.cfg"
VIDEO_PATH = "videos/"
